import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { api, errorMessage } from "../api";
import { Badge, Button, PageHeader, PageLoader } from "../components/ui";
import type { Site } from "../types";
import { formatDate } from "../lib";
type Order = { id:number; user_id:number; normalized_status:string; amount:number; currency:string; created_at:string|null; completed_at:string|null };
type Data = { items:Order[]; total:number; summary:{count_by_status:Record<string,number>; amount_by_status:Record<string,number>} };
const labels:Record<string,string>={pending:"待支付",paid:"已支付",recharging:"充值中",completed:"已完成",expired:"已过期",failed:"失败",cancelled:"已取消",unknown:"未知"};
export function BillingAuditPage(){const [sites,setSites]=useState<Site[]>([]),[site,setSite]=useState(""),[page,setPage]=useState(1),[data,setData]=useState<Data|null>(null),[error,setError]=useState("");useEffect(()=>{void api<Site[]>("/sites").then(v=>{setSites(v);if(v[0])setSite(v[0].id)}).catch(e=>setError(errorMessage(e)))},[]);useEffect(()=>{if(!site)return;setData(null);void api<Data>(`/operations/billing/orders?site_id=${encodeURIComponent(site)}&page=${page}&page_size=50`).then(setData).catch(e=>setError(errorMessage(e)))},[site,page]);return <div className="page"><PageHeader title="充值审计" description="只读查看 Sub2API 订单、支付状态和入账状态。" actions={<Link to="/overview">返回总览</Link>}/>{error&&<p className="quality-error" role="alert">{error}</p>}<div className="quality-actions"><label>站点 <select value={site} onChange={e=>{setSite(e.target.value);setPage(1)}}>{sites.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label></div>{!data?<PageLoader/>:<><section className="metric-grid">{Object.entries(data.summary.count_by_status).map(([k,v])=><article className="metric" key={k}><span>{labels[k]??k}</span><strong>{v}</strong><small>{(data.summary.amount_by_status[k]??0).toFixed(2)}</small></article>)}</section><section className="panel"><div className="quality-table-scroll"><table><thead><tr><th>订单</th><th>用户</th><th>状态</th><th>金额</th><th>创建时间</th><th>完成时间</th></tr></thead><tbody>{data.items.map(o=><tr key={o.id}><td>#{o.id}</td><td>{o.user_id}</td><td><Badge tone={o.normalized_status==="completed"?"success":o.normalized_status==="failed"?"danger":"warning"}>{labels[o.normalized_status]??"未知"}</Badge></td><td>{o.amount.toFixed(2)} {o.currency}</td><td>{formatDate(o.created_at??undefined)}</td><td>{formatDate(o.completed_at??undefined)}</td></tr>)}</tbody></table></div><div className="quality-actions"><Button disabled={page<=1} onClick={()=>setPage(page-1)}>上一页</Button><span>第 {page} 页 · 共 {data.total} 条</span><Button disabled={data.items.length<50} onClick={()=>setPage(page+1)}>下一页</Button></div></section></>}</div>}
