import { useCallback, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { api, errorMessage } from "../api";
import { Badge, Button, PageHeader, PageLoader } from "../components/ui";
import { formatDate } from "../lib";
type Site = {id:string;name:string;connection_state:string;last_inventory_at:string|null;last_reconcile_at:string|null;inventory_lag_seconds:number;reconcile_lag_seconds:number;usage_collection:{status?:string;message?:string;checked_at?:string};traffic_collection:{status?:string;message?:string;checked_at?:string}};
type Task = {kind:string;resource_type:string;started_at:string;finished_at:string|null;last_success_at:string|null;duration_ms:number|null;last_error:string;running:boolean};
type Data = {sites:Site[];tasks:Task[];workers:number;pool:{total:number;idle:number;acquired:number;acquire_count:number;empty_acquires:number};database:{count:number;errors:number};process?:{heap_mb:number;goroutines:number};checked_at:string};
export function OperationsPage(){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState("");const load=useCallback(async()=>{try{setData(await api<Data>("/operations"));setError("")}catch(e){setError(errorMessage(e))}},[]);useEffect(()=>{void load();const timer=setInterval(()=>void load(),15000);return()=>clearInterval(timer)},[load]);
 return <div className="page"><PageHeader title="运行状态" description="查看采集盲区、任务积压、租约、数据库和进程负载。" actions={<div className="quality-actions"><Link to="/">返回质量页</Link><Button onClick={()=>void load()}>刷新</Button></div>}/>{error&&<p className="quality-error" role="alert">{error}</p>}{!data&&!error?<PageLoader/>:data&&<>
 <section className="quality-editor"><h2>调度器自身健康</h2><div className="service-profile-facts"><span>{data.workers} 个 worker</span><span>数据库连接 {data.pool.acquired}/{data.pool.total}</span><span>等待连接 {data.pool.empty_acquires}</span><span>数据库操作 {data.database.count} · 错误 {data.database.errors}</span>{data.process&&<><span>堆内存 {data.process.heap_mb.toFixed(1)} MB</span><span>{data.process.goroutines} 个 goroutine</span></>}</div></section>
 <section className="quality-editor"><h2>站点采集</h2>{data.sites.map(site=><article className="quality-notification" key={site.id}><div><strong>{site.name}</strong><Badge tone={site.connection_state==="healthy"?"success":"danger"}>{site.connection_state}</Badge><span>库存积压 {site.inventory_lag_seconds}s</span><span>策略积压 {site.reconcile_lag_seconds}s</span></div><p>真实请求：{site.traffic_collection?.status??"未运行"} · 用量：{site.usage_collection?.status??"未运行"}</p><small className="quality-incident-time">库存 {formatDate(site.last_inventory_at??undefined)} · 策略 {formatDate(site.last_reconcile_at??undefined)}</small></article>)}</section>
 <section className="quality-editor"><h2>最近任务</h2>{data.tasks.length===0?<p>暂无任务记录。</p>:data.tasks.map((task,i)=><article className="quality-notification" key={`${task.resource_type}:${task.started_at}:${i}`}><div><Badge tone={task.last_error?"danger":task.running?"warning":"success"}>{task.last_error?"失败":task.running?"运行中":"完成"}</Badge><strong>{task.kind}</strong><span>{task.resource_type}</span><span>{formatDate(task.started_at)}</span></div><p>{task.last_error||`耗时 ${task.duration_ms??"—"} ms`}</p><small className="quality-incident-time">上次成功 {formatDate(task.last_success_at??undefined)}</small></article>)}</section>
 </>}</div>
}
