import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { api, errorMessage } from "../api";
import { Badge, Button, PageHeader, PageLoader } from "../components/ui";
import type { Site } from "../types";
import { formatDate } from "../lib";
type Code={id:number;code:string;type:string;status:string;value:number;used_by:number|null;expires_at:string|null;created_at:string|null};
type Data={items:Code[];total:number};
export function RedemptionsPage(){const [sites,setSites]=useState<Site[]>([]),[site,setSite]=useState(""),[page,setPage]=useState(1),[data,setData]=useState<Data|null>(null),[error,setError]=useState("");useEffect(()=>{void api<Site[]>("/sites").then(v=>{setSites(v);if(v[0])setSite(v[0].id)}).catch(e=>setError(errorMessage(e)))},[]);useEffect(()=>{if(!site)return;setData(null);void api<Data>(`/operations/redemptions?site_id=${encodeURIComponent(site)}&page=${page}&page_size=50`).then(setData).catch(e=>setError(errorMessage(e)))},[site,page]);return <div className="page"><PageHeader title="兑换码" description="只读查看 Sub2API 兑换码状态，兑换码已脱敏。" actions={<Link to="/overview">返回总览</Link>}/>{error&&<p className="quality-error" role="alert">{error}</p>}<div className="quality-actions"><label>站点 <select value={site} onChange={e=>{setSite(e.target.value);setPage(1)}}>{sites.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label></div>{!data?<PageLoader/>:<section className="panel"><div className="quality-table-scroll"><table><thead><tr><th>兑换码</th><th>类型</th><th>状态</th><th>额度</th><th>使用者</th><th>过期时间</th></tr></thead><tbody>{data.items.map(c=><tr key={c.id}><td>{c.code}</td><td>{c.type}</td><td><Badge tone={c.status==="unused"?"success":c.status==="expired"?"neutral":"warning"}>{c.status}</Badge></td><td>{c.value}</td><td>{c.used_by??"—"}</td><td>{formatDate(c.expires_at??undefined)}</td></tr>)}</tbody></table></div><div className="quality-actions"><Button disabled={page<=1} onClick={()=>setPage(page-1)}>上一页</Button><span>第 {page} 页 · 共 {data.total} 条</span><Button disabled={data.items.length<50} onClick={()=>setPage(page+1)}>下一页</Button></div></section>}</div>}
